version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 050725500261
      POSTGRES_DB: course_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak_db
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - app_network
    command: ["start-dev"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: course_app
    depends_on:
      - postgres
      - keycloak
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/course_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      KEYCLOAK_SERVER_URL: http://keycloak:8080
      KEYCLOAK_REALM: internship-realm
      KEYCLOAK_CLIENT_ID: course-app
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge