version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: internship-postgres
    environment:
      POSTGRES_DB: internship_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 050725500261
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U internship_user -d internship_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: